name: check

on:
  workflow_call:
    inputs:
      runner_image:
        required: true
        type: string

      build_type:
        required: true
        type: string

jobs:
  build:
    runs-on: ${{ inputs.runner_image }}

    steps:
      - name: Clone the source code
        uses: actions/checkout@v4

      - name: Install Rust
        run: |
          ./.github/workflows/scripts/install_rust.sh

    - name: Setup the command line build arguments
      id: build_type
      run: |
        if [[ "${{ matrix.build_type }}" == "Release" ]]; then
          echo "VALUE=--release" >> $GITHUB_OUTPUT
        fi

      - name: Run cargo check
        run: |
          cargo check \
            "${{ steps.build_type.outputs.VALUE }}" \
            --locked \
            --all-targets \
            --all-features \
            --tests \
            --workspace
