#
# Copyright (c) 2024-present, Alessandro Gario
# All rights reserved.
#
# This source code is licensed in accordance with the terms specified in
# the LICENSE file found in the root directory of this source tree.
#

name: clippy

on:
  workflow_call:
    inputs:
      runner_image:
        required: true
        type: string

      build_type:
        required: true
        type: string

jobs:
  clippy:
    runs-on: ${{ inputs.runner_image }}

    steps:
      - name: Clone the source code
        uses: actions/checkout@v4

      - name: Install Rust
        working-directory: ./.github/workflows/scripts
        run: |
          ./install_rust.sh

      - name: Setup the command line build arguments
        id: build_type
        run: |
          if [[ "${{ matrix.build_type }}" == "Release" ]]; then
            echo "VALUE=--release" >> $GITHUB_OUTPUT
          fi

      - name: Run cargo clippy
        continue-on-error: true
        run: |
          cargo clippy \
            ${{ steps.build_type.outputs.VALUE }} \
            --all-targets \
            --all-features \
            -- -D warnings
