#
# Copyright (c) 2024-present, Alessandro Gario
# All rights reserved.
#
# This source code is licensed in accordance with the terms specified in
# the LICENSE file found in the root directory of this source tree.
#

name: format

on:
  workflow_call:
    inputs:
      runner_image:
        required: true
        type: string

jobs:
  format:
    runs-on: ${{ inputs.runner_image }}

    steps:
      - name: Clone the source code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Rust
        working-directory: ./.github/workflows/scripts
        run: |
          ./install_rust.sh

      - name: Run cargo fmt
        run: |
          cargo fmt --all --check
